export type Lang = "en" | "zh";

export const copy = {
  en: {
    lab: "MING Lab",
    labZh: "明晨实验室",
    tagline: "Computational Neuroscience",
    affiliation: "Faculty of Medicine · University of Macau",
    pi: "Chen Ming",
    piTitle: "Assistant Professor",
    nav: {
      research: "Research",
      publications: "Publications",
      people: "People",
      news: "News",
      join: "Join",
      contact: "Contact",
      members: "Members",
      signIn: "Sign in",
      signOut: "Sign out",
    },
    hero: {
      kicker: "University of Macau",
      title: "MING Lab: Computational Neuroscience",
      lead: "We investigate the pathological mechanisms, progression, biomarkers of Alzheimer’s disease and pathological aging through large-scale multi-omics. Our final aim is to identify druggable targets and treatment strategies.",
      ctaResearch: "Explore the science",
      ctaJoin: "Join the lab",
      photoCaption: "Ming Lab · Faculty of Medicine, University of Macau",
    },
    stats: {
      citations: "Citations",
      papers: "Publications",
      focus: "Core focus",
      focusValue: "Alzheimer’s disease",
    },
    homeResearch: {
      kicker: "What we do",
      title: "From genetic risk to molecular targets",
      lead: "The lab integrates whole-genome sequencing, transcriptomics, proteomics, and metabolomics to map how genetic variation drives neurodegeneration — and where treatment can intervene.",
    },
    homePapers: {
      kicker: "Selected papers",
      title: "Work that shapes the field",
      all: "All publications",
    },
    homeNews: {
      kicker: "Lab notes",
      title: "Recent news",
      all: "All news",
    },
    homeJoin: {
      kicker: "Openings",
      title: "Build the next map of Alzheimer’s biology",
      lead: "We welcome motivated students and postdocs with a background in bioinformatics, genomics, statistics, or neuroscience. Macau is a compact, international research hub between the Greater Bay Area and the rest of the world.",
      cta: "See openings",
    },
    research: {
      kicker: "Research",
      title: "A computational path through neurodegeneration",
      lead: "Chen Ming’s group studies genetic risk factors — structural variations, SNPs, and causal genes — of neurodegenerative diseases by large-scale omics integration. The goal is to identify molecular targets and pathways for clinically effective treatment.",
      areas: [
        {
          id: "variants",
          title: "Genome-wide genetic variation",
          body: "Detection of copy-number variants, structural variants, and SNPs that affect neurodegenerative disease, with a particular focus on Alzheimer’s. Whole-genome sequencing is used to recover variation missed by arrays and exomes.",
          image: "./images/sequencing.jpg",
        },
        {
          id: "omics",
          title: "Multi-omics integration",
          body: "We stitch together whole-genome sequencing, transcriptomics, proteomics, and metabolic analysis into network models of disease. These maps reveal key regulators and candidate therapeutics that no single layer can show.",
          image: "./images/still-life.jpg",
        },
        {
          id: "populations",
          title: "Population genetics of disease",
          body: "Genetic architecture is not uniform across human populations. We decipher how risk variants and pathways differ, with implications for diagnosis and for therapies that must work beyond a single ancestry.",
          image: "./images/hero.jpg",
        },
        {
          id: "spatial",
          title: "Single-cell and spatial pathology",
          body: "Single-cell sequencing and spatial transcriptomics are used to locate disease programs in the brain — which cells fail, in which regions, and in what order — so that molecular targets can be placed in anatomical context.",
          image: "./images/spatial.jpg",
        },
      ],
      methodsTitle: "Methods we live in",
      methods: [
        "Whole-genome sequencing & structural variation",
        "Causal network inference",
        "Single-cell RNA-seq bioinformatics",
        "Spatial transcriptomics",
        "Multi-omics network modeling",
        "Population genetics",
      ],
    },
    publicationsPage: {
      kicker: "Papers",
      title: "Publications",
      lead: "Peer-reviewed work from the lab and from Chen Ming’s earlier research at the Icahn School of Medicine at Mount Sinai and the Chinese Academy of Sciences.",
      search: "Search titles, journals, authors",
      allYears: "All years",
      allRoles: "All roles",
      scholar: "Google Scholar",
      faculty: "Faculty profile",
      first: "First author",
      coFirst: "Co-first",
      corresponding: "Corresponding",
      coAuthor: "Co-author",
      citations: "citations",
      empty: "No papers match those filters.",
    },
    people: {
      kicker: "The group",
      title: "People",
      lead: "A computational biology laboratory in the Faculty of Medicine at the University of Macau.",
      piKicker: "Principal investigator",
      bio: "Chen Ming is an Assistant Professor and PhD supervisor in the Faculty of Medicine at the University of Macau. Her research addresses fundamental and translational questions in Alzheimer’s disease by integrating multi-omics data into functional regulatory networks and using computational biology to uncover disease mechanisms and prioritize druggable targets.",
      education: "Education",
      experience: "Appointments",
      awards: "Honours",
      service: "Professional service",
      funding: "Funding",
      officeHours: "Office hours",
      officeHoursValue: "Tuesday & Wednesday, 14:30–15:30",
      scholar: "Google Scholar",
      recruiting: "We are recruiting",
      recruitingLead:
        "PhD students, master’s students, postdoctoral fellows, and research assistants. If you care about Alzheimer’s genetics, multi-omics, or single-cell analysis of the brain, write to us.",
      groupPhoto: "The laboratory",
    },
    news: {
      kicker: "Updates",
      title: "News",
      lead: "Papers, press, and appointments.",
    },
    join: {
      kicker: "Openings",
      title: "Join the lab",
      lead: "We look for people who can think in both biology and data — and who want to spend years on a hard problem. Positions are considered on a rolling basis.",
      rolesTitle: "Who we hire",
      formTitle: "Write to us",
      formLead:
        "Tell us what you want to work on. A CV link (Google Drive, personal site, or OSF) is enough; no portal login is required.",
      name: "Name",
      email: "Email",
      position: "Position of interest",
      affiliation: "Current affiliation",
      message: "Research interests & background",
      submit: "Send application",
      sending: "Sending…",
      success: "Received. We will reply by email.",
      error: "Something went wrong. Please email chenming@um.edu.mo directly.",
      positions: [
        { id: "phd", label: "PhD student" },
        { id: "msc", label: "Master’s student" },
        { id: "postdoc", label: "Postdoctoral fellow" },
        { id: "ra", label: "Research assistant" },
        { id: "visitor", label: "Visiting scholar" },
        { id: "undergrad", label: "Undergraduate intern" },
      ],
      lookingFor: [
        {
          title: "Computational biologists",
          body: "Experience with WGS, RNA-seq, single-cell, or network inference. Python or R is expected; statistics is a plus.",
        },
        {
          title: "Quantitative wet-lab hybrids",
          body: "People who can talk to both a sequencer and a model. Spatial, proteomic, or iPSC experience is welcome.",
        },
        {
          title: "Curious generalists",
          body: "A strong first-principles mind matters more than a perfect keyword match. Show us a piece of work you are proud of.",
        },
      ],
    },
    contact: {
      kicker: "Visit",
      title: "Contact",
      lead: "The lab sits in building E12 on the University of Macau campus, Hengqin, Macao SAR.",
      office: "Office",
      lab: "Laboratory",
      team: "Team office",
      email: "Email",
      hours: "Consultation",
      formTitle: "Send a message",
      name: "Name",
      emailField: "Email",
      subject: "Subject",
      message: "Message",
      submit: "Send",
      sending: "Sending…",
      success: "Message received.",
      error: "Could not send. Please email chenming@um.edu.mo.",
    },
    login: {
      kicker: "Lab members",
      title: "Sign in",
      lead: "Members of the lab can sign in to keep journal-club notes and track applications. Visitors applying to join do not need an account.",
      continue: "Continue with",
      disabled: "Sign-in is currently disabled.",
      back: "Back to the lab",
    },
    members: {
      kicker: "Internal",
      title: "Members’ desk",
      lead: "A quiet place for notes on papers we discuss, and a record of anything you have sent the lab.",
      notes: "Journal club notes",
      notesLead: "Pick a paper and leave a private note. Only you can see it.",
      paper: "Paper",
      note: "Your note",
      save: "Save note",
      saving: "Saving…",
      saved: "Saved.",
      applications: "Your applications",
      noApplications: "No applications on file for this account.",
      noNotes: "No notes yet.",
      guest: "Sign in to use the members’ desk.",
    },
    footer: {
      rights: "Ming Lab, University of Macau",
      scholar: "Scholar",
      faculty: "UM profile",
    },
    education: [
      { when: "2017", what: "PhD, Chinese Academy of Sciences" },
      { when: "2010", what: "BSc, University of Science and Technology of China" },
    ],
    experience: [
      {
        when: "11/2022 – present",
        what: "Assistant Professor, Faculty of Medicine, University of Macau",
      },
      {
        when: "03/2022 – 09/2022",
        what: "Instructor, Icahn School of Medicine at Mount Sinai",
      },
      {
        when: "11/2017 – 03/2022",
        what: "Postdoctoral Fellow, Icahn School of Medicine at Mount Sinai",
      },
    ],
    awards: [{ when: "04/2020", what: "Promising Young Investigator Award, Mount Sinai" }],
    service: [
      "Committee member, Neuroregeneration and Repair Professional Committee of the Chinese Research Hospital Association",
      "Youth council member, Mitochondria Branch of the Biophysical Society of China",
      "Council member, Macau Stem Cell Research Association",
      "Council member, Macau Bioinformatics Society",
      "Young Editorial Board Member and Special Issue Editor, Journal of Genetics and Genomics (JGG)",
      "Reviewer for Science Translational Medicine, Nature Communications, Science Advances, and Alzheimer’s & Dementia",
      "Trainee, 18th Cell Huangpu Workshop, Chinese Society for Cell Biology",
    ],
    funding:
      "In the past five years she has led an NSFC International (Regional) Cooperation and Exchange project, multiple Macao Science and Technology Development Fund (FDCT) grants, a national-laboratory special-project sub-topic, and several University of Macau intramural grants, and has taken part in an FDCT Key R&D project.",
  },
  zh: {
    lab: "明晨实验室",
    labZh: "MING Lab",
    tagline: "计算神经科学",
    affiliation: "澳门大学医学院",
    pi: "明晨",
    piTitle: "助理教授",
    nav: {
      research: "研究",
      publications: "论文",
      people: "成员",
      news: "动态",
      join: "加入",
      contact: "联络",
      members: "内部",
      signIn: "登录",
      signOut: "登出",
    },
    hero: {
      kicker: "澳门大学",
      title: "MING Lab：计算神经科学",
      lead: "我们以大规模多组学方法研究阿尔茨海默病与病理性老化的病理机制、进程与生物标志物。最终目标是鉴定可成药靶点与治疗策略。",
      ctaResearch: "了解研究方向",
      ctaJoin: "加入实验室",
      photoCaption: "明晨实验室 · 澳门大学医学院",
    },
    stats: {
      citations: "被引",
      papers: "论文",
      focus: "核心方向",
      focusValue: "阿尔茨海默病",
    },
    homeResearch: {
      kicker: "研究方向",
      title: "从遗传风险到分子靶点",
      lead: "实验室整合全基因组测序、转录组、蛋白质组与代谢组，绘制遗传变异如何驱动神经退化，以及治疗可以介入的节点。",
    },
    homePapers: {
      kicker: "代表论文",
      title: "构成领域的工作",
      all: "全部论文",
    },
    homeNews: {
      kicker: "实验室动态",
      title: "近期消息",
      all: "全部动态",
    },
    homeJoin: {
      kicker: "招募",
      title: "一起绘制阿尔茨海默病的下一张分子地图",
      lead: "欢迎具备生物资讯、基因组学、统计或神经科学背景的学生与博士后。澳门是连接粤港澳大湾区与国际学术网络的紧凑研究枢纽。",
      cta: "查看职位",
    },
    research: {
      kicker: "研究",
      title: "一条通向神经退化的计算路径",
      lead: "明晨课题组透过大规模组学整合，研究神经退化疾病的遗传风险因素（结构变异、SNP 与因果基因），目标是找出具有临床意义的分子靶点与通路。",
      areas: [
        {
          id: "variants",
          title: "全基因组遗传变异",
          body: "检测影响神经退化疾病（尤其是阿尔茨海默病）的拷贝数变异、结构变异与 SNP。以全基因组测序捕捉晶片与外显子组容易遗漏的变异。",
          image: "./images/sequencing.jpg",
        },
        {
          id: "omics",
          title: "多组学整合",
          body: "将全基因组测序、转录组、蛋白质组与代谢分析编织成疾病网络模型，揭示单一层次无法看见的关键调控因子与候选疗法。",
          image: "./images/still-life.jpg",
        },
        {
          id: "populations",
          title: "疾病的群体遗传学",
          body: "遗传架构在不同人群中并不均一。我们解析风险变异与通路的人群差异，服务诊断与可跨族群生效的治疗。",
          image: "./images/hero.jpg",
        },
        {
          id: "spatial",
          title: "单细胞与空间病理",
          body: "以单细胞测序与空间转录组定位大脑中的疾病程式——哪些细胞、在哪些脑区、以何种次序失效——把分子靶点放回解剖学语境。",
          image: "./images/spatial.jpg",
        },
      ],
      methodsTitle: "方法学",
      methods: [
        "全基因组测序与结构变异",
        "因果网络推断",
        "单细胞转录组生物资讯",
        "空间转录组",
        "多组学网络建模",
        "群体遗传学",
      ],
    },
    publicationsPage: {
      kicker: "论文",
      title: "发表",
      lead: "实验室论文，以及明晨于西奈山伊坎医学院与中国科学院期间的工作。",
      search: "搜寻题目、期刊、作者",
      allYears: "全部年份",
      allRoles: "全部角色",
      scholar: "Google 学术",
      faculty: "学院主页",
      first: "第一作者",
      coFirst: "共同第一",
      corresponding: "通讯作者",
      coAuthor: "合作",
      citations: "次引用",
      empty: "没有符合条件的论文。",
    },
    people: {
      kicker: "课题组",
      title: "成员",
      lead: "澳门大学医学院的计算生物学实验室。",
      piKicker: "课题组负责人",
      bio: "明晨为澳门大学医学院助理教授、博士生导师。研究以多组学整合构建功能调控网络，并运用计算生物学方法解析阿尔茨海默病的疾病机制与可成药靶点。",
      education: "教育",
      experience: "任职",
      awards: "荣誉",
      service: "学术服务",
      funding: "科研资助",
      officeHours: "咨询时间",
      officeHoursValue: "星期二、三 14:30–15:30",
      scholar: "Google 学术",
      recruiting: "正在招募",
      recruitingLead:
        "博士生、硕士生、博士后与研究助理。若你关心阿尔茨海默病遗传学、多组学或大脑单细胞分析，请来信。",
      groupPhoto: "课题组合影",
    },
    news: {
      kicker: "动态",
      title: "消息",
      lead: "论文、媒体与任职。",
    },
    join: {
      kicker: "招募",
      title: "加入实验室",
      lead: "我们寻找能同时以生物学与数据思考、并愿意在难题上停留数年的人。职位滚动审核。",
      rolesTitle: "我们寻找",
      formTitle: "来信",
      formLead:
        "告诉我们你想做什么。附上履历连结（云端硬碟、个人网站或 OSF）即可，无需先注册。",
      name: "姓名",
      email: "电邮",
      position: "意向职位",
      affiliation: "目前单位",
      message: "研究兴趣与背景",
      submit: "送出申请",
      sending: "送出中…",
      success: "已收到，我们会以电邮回复。",
      error: "送出失败。请直接电邮 chenming@um.edu.mo。",
      positions: [
        { id: "phd", label: "博士生" },
        { id: "msc", label: "硕士生" },
        { id: "postdoc", label: "博士后" },
        { id: "ra", label: "研究助理" },
        { id: "visitor", label: "访问学者" },
        { id: "undergrad", label: "本科实习" },
      ],
      lookingFor: [
        {
          title: "计算生物学家",
          body: "具备 WGS、RNA-seq、单细胞或网络推断经验。需 Python 或 R；统计为加分项。",
        },
        {
          title: "定量与实验的交界",
          body: "能同时与测序仪和模型对话。欢迎空间组学、蛋白质组或 iPSC 经验。",
        },
        {
          title: "有好奇心的通才",
          body: "第一性原理比关键词匹配更重要。请给我们一件你引以为傲的工作。",
        },
      ],
    },
    contact: {
      kicker: "到访",
      title: "联络",
      lead: "实验室位于澳门大学（横琴）E12 楼。",
      office: "办公室",
      lab: "实验室",
      team: "团队办公室",
      email: "电邮",
      hours: "咨询时间",
      formTitle: "留言",
      name: "姓名",
      emailField: "电邮",
      subject: "主旨",
      message: "内容",
      submit: "送出",
      sending: "送出中…",
      success: "已收到留言。",
      error: "无法送出。请电邮 chenming@um.edu.mo。",
    },
    login: {
      kicker: "成员",
      title: "登录",
      lead: "实验室成员可登录以保存文献讨论笔记、查看申请纪录。投递申请无需帐号。",
      continue: "使用以下方式继续",
      disabled: "目前未开放登录。",
      back: "返回实验室",
    },
    members: {
      kicker: "内部",
      title: "成员工作台",
      lead: "为文献讨论留下私人笔记，并查看你送出过的申请。",
      notes: "文献会笔记",
      notesLead: "选择一篇论文并留下只有你能看见的笔记。",
      paper: "论文",
      note: "笔记",
      save: "储存",
      saving: "储存中…",
      saved: "已储存。",
      applications: "你的申请",
      noApplications: "此帐号尚无申请纪录。",
      noNotes: "尚无笔记。",
      guest: "请登录以使用成员工作台。",
    },
    footer: {
      rights: "明晨实验室 · 澳门大学",
      scholar: "学术搜寻",
      faculty: "学院主页",
    },
    education: [
      { when: "2017", what: "中国科学院 博士" },
      { when: "2010", what: "中国科学技术大学 学士" },
    ],
    experience: [
      {
        when: "2022.11 – 至今",
        what: "澳门大学医学院助理教授",
      },
      {
        when: "2022.03 – 2022.09",
        what: "西奈山伊坎医学院讲师",
      },
      {
        when: "2017.11 – 2022.03",
        what: "西奈山伊坎医学院博士后研究员",
      },
    ],
    awards: [{ when: "2020.04", what: "西奈山 Promising Young Investigator Award" }],
    service: [
      "中国研究型医院学会神经再生与修复专业委员会委员",
      "中国生物物理学会线粒体分会青年理事",
      "澳门干细胞研究协会理事",
      "澳门生物信息学会理事",
      "Journal of Genetics and Genomics (JGG) 青年编委及特刊编委",
      "Science Translational Medicine、Nature Communications、Science Advances、Alzheimer’s & Dementia 审稿人",
      "中国细胞生物学学会细胞黄浦研修班第18期学员",
    ],
    funding:
      "近五年主持基金委国际（地区）交流与合作项目一项、澳门科学技术发展基金多项、国家实验室专项攻关子课题负责人、主持澳门大学校内基金多项，并参与澳门科学技术发展基金重点研发项目一项。",
  },
} as const;

export type NewsLink = {
  labelEn: string;
  labelZh: string;
  href: string;
};

export type NewsItem = {
  id: string;
  date: string;
  href: string;
  image?: string;
  links?: readonly NewsLink[];
  en: { title: string; body: string };
  zh: { title: string; body: string };
};

export const newsItems: NewsItem[] = [
  {
    id: "sciencenet-2025",
    date: "2025-12",
    href: "https://news.sciencenet.cn/sbhtmlnews/2025/12/387623.shtm",
    image: "./images/news/sciencenet-antibody.jpg",
    links: [
      {
        labelEn: "China Science Daily",
        labelZh: "中国科学报",
        href: "https://news.sciencenet.cn/sbhtmlnews/2025/12/387623.shtm",
      },
    ],
    en: {
      title: "Press news for the 18th WILLA training for junior PIs",
      body: "China Science Daily reports on the 18th WILLA training for junior principal investigators.",
    },
    zh: {
      title: "第18期 WILLA 青年课题组长研修报导",
      body: "《中国科学报》报导第18期 WILLA 青年课题组长（junior PI）研修。",
    },
  },
  {
    id: "nsclc-sotorasib",
    date: "2025",
    href: "https://www.163.com/dy/article/L3GC3D6S0532HZIO.html",
    image: "./images/news/nsclc-163.png",
    links: [
      {
        labelEn: "NetEase",
        labelZh: "网易",
        href: "https://www.163.com/dy/article/L3GC3D6S0532HZIO.html",
      },
      {
        labelEn: "WeChat",
        labelZh: "微信",
        href: "https://mp.weixin.qq.com/s/S5ZDmQNc9aPgXu1jy3RpTQ?scene=1&click_id=729134948",
      },
    ],
    en: {
      title: "Press coverage of peripheral-blood immune mechanisms of sotorasib resistance in NSCLC",
      body: "Media reports discuss immune mechanisms of resistance to sotorasib in non-small-cell lung cancer, based on peripheral-blood analysis connected to the lab’s computational work.",
    },
    zh: {
      title: "媒体报导：非小细胞肺癌索托拉西布耐药的外周血免疫机制",
      body: "网易与微信公众号报导非小细胞肺癌对索托拉西布产生耐药的外周血免疫机制，与课题组的计算分析相关。",
    },
  },
  {
    id: "neuron-2024",
    date: "2024-05-14",
    href: "https://www.um.edu.mo/zh-hant/news-and-press-releases/campus-news/detail/58321/",
    image: "./images/news/sohu-ptau217.png",
    links: [
      {
        labelEn: "University of Macau",
        labelZh: "澳门大学",
        href: "https://www.um.edu.mo/zh-hant/news-and-press-releases/campus-news/detail/58321/",
      },
      {
        labelEn: "Sohu",
        labelZh: "搜狐",
        href: "https://www.sohu.com/a/770894360_121123911",
      },
    ],
    en: {
      title: "Press on the p-tau217 monoclonal antibody mAb2A7",
      body: "UM News and Sohu cover the Neuron study co-first-authored by Chen Ming: a monoclonal antibody (mAb2A7) that specifically targets p-tau217 and reduces tauopathy in mice.",
    },
    zh: {
      title: "媒体报导特异性靶向 p-tau217 的单克隆抗体 mAb2A7",
      body: "澳门大学新闻与搜狐报导明晨共同第一作者的 Neuron 工作：单克隆抗体 mAb2A7 特异性靶向 p-tau217，并改善小鼠 tau 病变。",
    },
  },
  {
    id: "bib-2025",
    date: "2025-12-08",
    href: "https://doi.org/10.1093/bib/bbaf652",
    en: {
      title: "Corresponding-author paper on WGS variant-calling pipelines in twins",
      body: "Tan, Sun, Yu, Fu, Ming and Liu benchmark eight whole-genome sequencing variant callers in monozygotic twins, published in Briefings in Bioinformatics.",
    },
    zh: {
      title: "通讯作者论文：同卵双胞胎全基因组变异检测流程评估",
      body: "Tan、Sun、Yu、Fu、明晨与 Liu 以同卵双胞胎基因组评估八套全基因组测序变异检测流程，发表于 Briefings in Bioinformatics。",
    },
  },
  {
    id: "narcancer-2024",
    date: "2024-11-15",
    href: "https://doi.org/10.1093/narcan/zcae043",
    en: {
      title: "Corresponding-author paper on dual roles of TFEB in pan-cancer",
      body: "Luo, Wang, Fu and colleagues integrate transcriptional and epigenetic regulation of TFEB in NAR Cancer, with Chen Ming as corresponding author.",
    },
    zh: {
      title: "通讯作者论文：TFEB 在泛癌中的双重功能",
      body: "骆静方、王世佳、付家静等整合 TFEB 的转录与表观调控，发表于 NAR Cancer，明晨为通讯作者。",
    },
  },
  {
    id: "alzforum-2024",
    date: "2024-04-11",
    href: "https://www.alzforum.org/news/research-news/p-tau217-immunotherapy-alleviates-tangle-pathology-mice",
    en: {
      title: "Alzforum covers the p-tau217 antibody study",
      body: "The field commentary highlights antibodies generated against mid-domain tau residues 209–223 phosphorylated at threonine 217, and their effect on tangle pathology.",
    },
    zh: {
      title: "Alzforum 报导 p-tau217 抗体研究",
      body: "评论聚焦针对 tau 209–223 位点、苏氨酸 217 磷酸化的抗体，以及其对缠结病理的影响。",
    },
  },
  {
    id: "frontiers-2023",
    date: "2023-11-02",
    href: "https://doi.org/10.3389/fnagi.2023.1241412",
    en: {
      title: "Corresponding-author paper on CNVs and longevity in late-onset AD",
      body: "A causality-network analysis of copy-number variation in late-onset Alzheimer’s, published in Frontiers in Aging Neuroscience.",
    },
    zh: {
      title: "通讯作者论文：拷贝数变异与晚发型阿尔茨海默病寿命",
      body: "以因果网络分析晚发型阿尔茨海默病中的拷贝数变异，发表于 Frontiers in Aging Neuroscience。",
    },
  },
  {
    id: "jgg-2023",
    date: "2023-01-01",
    href: "https://www.sciencedirect.com/journal/journal-of-genetics-and-genomics",
    en: {
      title: "Junior editor, Journal of Genetics and Genomics",
      body: "Chen Ming joined the editorial board of JGG and the Macau Medical Journal, and was appointed to the Chinese Research Hospital Association committee on neural regeneration and repair.",
    },
    zh: {
      title: "担任 Journal of Genetics and Genomics 青年编委",
      body: "明晨加入 JGG 与澳门医学杂志编委会，并任中国研究型医院学会神经再生与修复专业委员会委员。",
    },
  },
  {
    id: "um-2022",
    date: "2022-11-01",
    href: "https://fmd.um.edu.mo/academic/chen-ming/",
    en: {
      title: "Chen Ming joins the University of Macau",
      body: "After postdoctoral training and an instructorship at Mount Sinai, Chen Ming started as assistant professor in the Faculty of Health Sciences.",
    },
    zh: {
      title: "明晨加入澳门大学",
      body: "于西奈山完成博士后与讲师训练后，明晨出任健康科学学院助理教授。",
    },
  },
  {
    id: "award-2020",
    date: "2020-04-01",
    href: "https://icahn.mssm.edu/",
    en: {
      title: "Promising Young Investigator Award, Mount Sinai",
      body: "Travel award recognising early independent work in neurodegeneration genomics.",
    },
    zh: {
      title: "西奈山 Promising Young Investigator Award",
      body: "表彰神经退化基因组学方向的早期独立工作。",
    },
  },
] as const;

export const contactDetails = {
  email: "chenming@um.edu.mo",
  officePhone: "+853 8822 9117",
  officeRoom: "E12-1035",
  labPhone: "+853 8822 9121",
  labRoom: "E12-3072",
  teamPhone: "+853 8822 2014",
  teamRoom: "E12-1025, 1036",
  facultyUrl: "https://fmd.um.edu.mo/academic/chen-ming/",
  scholarUrl: "https://scholar.google.com/citations?user=ldh8w70AAAAJ&hl=en",
  campus: "University of Macau, E12, Avenida da Universidade, Taipa, Macao SAR",
};
